### ISSUE TITLE
NULL values are implicitly serialized

### ISSUE THREAD

**Issue by blag** [EncoreTechnologies/orquestaconvert#10]
Converting `null` values is difficult because the ruamel package doesn't explicitly serialize `None` to `null` - it simply leaves the value blank.

Observe:

```yaml
input:
  - foo
  - bar
  - baz: null
```

Which reserializes to:

```yaml
input:
  - foo
  - bar
  - baz:  # implicit null
```

Luckily empty values are deserialized to `None` anyway, so this doesn't break anything, but it does impact readability.

This is reported in [ruamel issue #169](https://bitbucket.org/ruamel/yaml/issues/169/roundtripdumper-dumps-null-values).
